#!/usr/bin/env node

// Artwork-only tool: node scripts/gen-icons.js (requires librsvg's rsvg-convert).
// Ordinary extension builds copy the committed PNGs and do not need librsvg.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ICONS = path.join(ROOT, 'src/icons');
const OUTPUT = path.join(ROOT, 'artifacts/brand');
const read = name => fs.readFileSync(path.join(ROOT, 'branding', name), 'utf8');
const body = source => source.match(/<g id="vacuum"[\s\S]*<\/g>/)[0];
const mark = body(read('little-vacuum.svg'));
const toolbar = body(read('toolbar.svg'));
// Chrome cannot select theme_icons; this coral clears 3:1 on the measured
// white and #3c3c3c toolbars without changing the approved optical silhouette.
const chromeToolbarColor = '#d76b58';
const chromeToolbar = toolbar.replace('#c45140', chromeToolbarColor);
const sizes = [16, 20, 24, 32, 48, 64, 96, 128];
const inventory = [];
const svg = (width, height, content) => `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">\n<!-- Generated by scripts/gen-icons.js from the approved editable branding masters. -->\n${content}\n</svg>\n`;
const symbol = (id, viewBox, content) => `<symbol id="${id}" viewBox="${viewBox}">${content}</symbol>`;
const use = (id, x, y, width, height = width) => `<use xlink:href="#${id}" x="${x}" y="${y}" width="${width}" height="${height}"/>`;

function render(source, destination, width, height = width, opaque = false) {
  const args = ['--width', String(width), '--height', String(height)];
  if (opaque) args.push('--background-color', '#ba493b');
  // Fixed executable and argv; SVG is passed on stdin, never interpolated into a shell.
  const png = execFileSync('rsvg-convert', args, { input: source, maxBuffer: 8 * 1024 * 1024 });
  fs.writeFileSync(destination, png);
  inventory.push(`${path.relative(ROOT, destination)}: ${width}x${height}`);
}

fs.mkdirSync(ICONS, { recursive: true });
fs.mkdirSync(OUTPUT, { recursive: true });

// Store icons retain the cream tile from the approved promo, with a 12.5% inset.
const store = svg(128, 128, `<defs>${symbol('mark', '0 0 32 32', mark)}</defs>
<rect id="tile" x="16" y="16" width="96" height="96" rx="23" fill="#fff6ee"/>
${use('mark', 32, 32, 64)}`);
fs.writeFileSync(path.join(OUTPUT, 'store-icon.svg'), store);
for (const size of sizes) {
  render(store, path.join(ICONS, `icon-${size}.png`), size);
  render(svg(16, 16, toolbar), path.join(ICONS, `toolbar-${size}.png`), size);
  if (size <= 64) render(svg(16, 16, chromeToolbar), path.join(ICONS, `toolbar-chrome-${size}.png`), size);
  render(svg(16, 16, toolbar.replace('#c45140', '#ffab99')), path.join(ICONS, `toolbar-light-${size}.png`), size);
}
// Header mark follows the popup's color scheme without recoloring action icons.
const popup = svg(16, 16, `<style>@media (prefers-color-scheme: dark) { #vacuum { color: #ffab99; } }</style>\n${toolbar}`);
fs.writeFileSync(path.join(ICONS, 'brand.svg'), popup);

const page = symbol('page', '0 0 80 90', '<path d="M12 2H44L53 13H68Q78 13 78 23V78Q78 88 68 88H12Q2 88 2 78V12Q2 2 12 2Z" fill="currentColor"/>');
const defs = `<defs>${symbol('mark', '0 0 32 32', mark)}${page}</defs>`;
// The selected concept's small promo composition is preserved.
const small = svg(440, 280, `${defs}
<rect id="background" width="440" height="280" fill="#ba493b"/>
<path id="ground" d="M0 244L440 135V280H0Z" fill="#a13c2f"/>
<g id="airflow" stroke="#f2907e" stroke-width="2" fill="none">
<path d="M0 98C112 98 75 230 216 212"/><path d="M0 120C102 120 83 235 216 229"/></g>
<g id="pages" color="#f9beac" transform="rotate(-18 53 115)">${use('page', 37, 97, 32, 37)}</g>
<g color="#ffe1d6" transform="rotate(16 93 182)">${use('page', 81, 168, 24, 28)}</g>
<rect id="tile" x="150" y="67" width="144" height="144" rx="35" fill="#fff6ee"/>
${use('mark', 174, 91, 96)}
<circle id="accent" cx="355" cy="73" r="8" fill="#f2907e"/>`);
const marquee = svg(1400, 560, `${defs}
<rect id="background" width="1400" height="560" fill="#ba493b"/>
<path id="ground" d="M0 540L1400 184V560H0Z" fill="#a13c2f"/>
<g id="airflow" stroke="#f2907e" stroke-width="3" fill="none">
<path d="M-40 136C333 64 343 523 732 417"/><path d="M-40 176C312 132 360 536 732 451"/></g>
<g id="pages" color="#f9beac" transform="rotate(-18 263 203)">${use('page', 231, 167, 64, 74)}</g>
<g color="#ffe1d6" transform="rotate(16 440 381)">${use('page', 416, 353, 48, 56)}</g>
<rect id="tile" x="556" y="136" width="288" height="288" rx="70" fill="#fff6ee"/>
${use('mark', 604, 184, 192)}
<circle id="accent" cx="1070" cy="146" r="16" fill="#f2907e"/>`);
for (const [name, source, width, height] of [
  ['promo-small', small, 440, 280], ['promo-marquee', marquee, 1400, 560],
]) {
  fs.writeFileSync(path.join(OUTPUT, `${name}.svg`), source);
  render(source, path.join(OUTPUT, `${name}.png`), width, height, true);
}

// Embed the exported PNG bytes so the proof shows actual pixel-size outputs,
// rather than rerendering the large master and hiding small-icon defects.
const image = (file, x, y, width, height = width) => `<image x="${x}" y="${y}" width="${width}" height="${height}" xlink:href="data:image/png;base64,${fs.readFileSync(file).toString('base64')}"/>`;
let samples = '';
for (const [column, size] of [16, 20, 24, 32, 48].entries()) {
  const x = 84 + column * 79;
  samples += image(path.join(ICONS, `toolbar-chrome-${size}.png`), x, 710 - size / 2, size);
  samples += image(path.join(ICONS, `toolbar-chrome-${size}.png`), x, 790 - size / 2, size);
  samples += image(path.join(ICONS, `toolbar-light-${size}.png`), x + 562, 790 - size / 2, size);
  samples += image(path.join(ICONS, `toolbar-${size}.png`), x + 562, 710 - size / 2, size);
  samples += `<text x="${x}" y="844" font-size="12" fill="#58545d">${size}px</text><text x="${x + 562}" y="844" font-size="12" fill="#58545d">${size}px</text>`;
}
const board = svg(1200, 900, `${defs}
<rect width="1200" height="900" fill="#f4f3f0"/>
<g font-family="DejaVu Sans, sans-serif" fill="#202027">
<text x="48" y="54" font-size="13" letter-spacing="1.6" fill="#58545d">AARON'S TAB VACUUM / LITTLE VACUUM</text>
<text x="48" y="107" font-size="34" font-weight="700">Search, sort &amp; clean up.</text>
<text x="48" y="141" font-size="16" fill="#58545d">The selected identity. Exported assets, with toolbar icons shown at actual pixel sizes.</text>
<g transform="translate(48 182)">${use('mark', 0, 0, 56)}<text x="72" y="42" font-size="36" font-weight="700" letter-spacing="-1">Aaron's Tab Vacuum</text></g>
${image(path.join(OUTPUT, 'promo-small.png'), 48, 267, 440, 280)}
<text x="48" y="578" font-size="14" fill="#58545d">440 × 280 promo · approved composition</text>
<text x="610" y="217" font-size="17" font-weight="700">Store icon</text>
${image(path.join(ICONS, 'icon-128.png'), 610, 242, 128)}
<text x="765" y="287" font-size="15">128px PNG</text>
<text x="765" y="314" font-size="14" fill="#58545d">96px tile · 16px transparent padding</text>
${image(path.join(OUTPUT, 'promo-marquee.png'), 610, 395, 540, 216)}
<text x="610" y="635" font-size="14" fill="#58545d">1400 × 560 marquee · shown reduced</text>
<text x="48" y="654" font-size="16" font-weight="700">Chrome · one coral mark for both themes</text>
<text x="610" y="654" font-size="16" font-weight="700">Firefox · theme-aware ink</text>
<rect x="48" y="672" width="500" height="74" rx="8" fill="#ffffff"/>
<rect x="48" y="752" width="500" height="74" rx="8" fill="#3c3c3c"/>
<rect x="610" y="672" width="540" height="74" rx="8" fill="#ffffff"/>
<rect x="610" y="752" width="540" height="74" rx="8" fill="#26252b"/>
${samples}
<text x="48" y="881" font-size="13" fill="#58545d">Review board only. No fabricated product screenshots. Existing violet action and focus accents stay unchanged.</text>
</g>`);
fs.writeFileSync(path.join(OUTPUT, 'review-board.svg'), board);
render(board, path.join(OUTPUT, 'review-board.png'), 1200, 900, true);
fs.writeFileSync(path.join(OUTPUT, 'inventory.txt'), `${inventory.join('\n')}\n`);
console.log(`Generated ${inventory.length} PNGs, SVG exports and inventory in src/icons and artifacts/brand.`);
